### ISSUE TITLE
Biter and String process extension not working

### ISSUE THREAD

**Issue by fath11** [Gandi-IDE/custom-extension#118]
Both of them only return blank. 
![image](https://github.com/Gandi-IDE/custom-extension/assets/124476952/96c8e3ee-6678-4ecd-9529-7f0606920289)
![Screenshot 2023-09-26 215758](https://github.com/Gandi-IDE/custom-extension/assets/124476952/96d25d5c-edd4-4ba0-a2be-034e3c71dde5)

**Comment by fath11** [comment]
all blocks inside of them are the same

**Comment by sylarhcn** [comment]
<img width="192" alt="image" src="https://github.com/Gandi-IDE/custom-extension/assets/1246288/aef453d6-198b-49d9-b113-b7b4602195d0">
<img width="287" alt="image" src="https://github.com/Gandi-IDE/custom-extension/assets/1246288/fca4b623-d4f5-4745-ab74-a88a5a747180">

I tried your case and everything worked fine。Can you provide more info？

**Comment by fath11** [comment]
![image](https://github.com/Gandi-IDE/custom-extension/assets/124476952/aaba1bb7-5e74-49fb-8f7b-358595d2ca14)
this block is giving out this error

**Comment by fath11** [comment]
the problem occurs on cocrea version of gandi but not ccw version. Is it possible that the fix is not being added to our gandi?

**Comment by fath11** [comment]
> ![image](https://user-images.githubusercontent.com/124476952/270976864-aaba1bb7-5e74-49fb-8f7b-358595d2ca14.png) this block is giving out this error

this problem still happens on ccw

**Comment by qxsck** [comment]
> 它们都只返回空白。 ![图像](https://usercontent.githubfast.com/user-images/124476952/270680945-96c8e3ee-6678-4ecd-9529-7f0606920289.png) ![截图 2023-09-26 215758](https://usercontent.githubfast.com/user-images/124476952/270681072-96d25d5c-edd4-4ba0-a2be-034e3c71dde5.png)

Is this question in Cocrea or CCW's Gandi? Is there a problem with both Chinese and English?

**Comment by fath11** [comment]
> Is this question in Cocrea or CCW's Gandi? Is there a problem with both Chinese and English?

both

string extension seems to be working properly, but biter is still broken

**Comment by qxsck** [comment]
> > 这个问题是在可克雷还是 CCW 的 Gandi 中？中文和英文都有问题吗？
> 
> 双
> 
> 字符串扩展似乎工作正常，但 biter 仍然损坏

thanks

**Comment by FurryR** [comment]
> ![image](https://user-images.githubusercontent.com/124476952/270976864-aaba1bb7-5e74-49fb-8f7b-358595d2ca14.png) this block is giving out this error

Please follow the top of the error stacks (`Biter.Rad2Rad`), and post the exception source. This helps us identify the defect.

**Comment by fath11** [comment]
> Please follow the top of the error stacks (`Biter.Rad2Rad`), and post the exception source. This helps us identify the defect.

![image](https://github.com/Gandi-IDE/custom-extension/assets/124476952/7a14a37b-61d2-4c1a-94bb-54caee482fa8)
