### ISSUE TITLE
请问一下可以把tw扩展兼容一下吗

### ISSUE THREAD

**Issue by WP-Studio01** [Gandi-IDE/custom-extension#179]
我现在用tw扩展做的游戏无法传到gandi上，扩展链接输了也不行

**Comment by qxsck** [comment]
> 我现在用tw扩展做的游戏无法传到gandi上，扩展链接输了也不行

只有部分tw拓展在gandi是支持的

**Comment by WP-Studio01** [comment]
哪些



在 2024-02-08 20:23:21，"qxs_ck" ***@***.***> 写道：

我现在用tw扩展做的游戏无法传到gandi上，扩展链接输了也不行

只有部分tw拓展在gandi是支持的

**Comment by fath11** [comment]
#180

**Comment by sylarhcn** [comment]
兼容不了的，因为很多 tw 扩展是基于 gandi 没有的 api 写的。
如果是修改扩展源码，搬运到 gandi 的话，你可以自己尝试，官方应该不会去做。
但是记得注意遵守别人的开源协议。

**Comment by fath11** [comment]
Turbowarp recently changed its license. Will that effect how extensions are ported, or we shouldn't care at all?
