### ISSUE TITLE
IndexedDB not working as expected

### ISSUE THREAD

**Issue by fath11** [Gandi-IDE/custom-extension#185]
It gave the content of the description instead of the value
![image](https://github.com/Gandi-IDE/custom-extension/assets/124476952/44fe605b-8bc3-477a-a2ed-15725709eae2)

![image](https://github.com/Gandi-IDE/custom-extension/assets/124476952/01f79df8-4888-47f3-92fa-3cbd5d08ac6b)

**Comment by sylarhcn** [comment]
@little-starts 白猫看这里，check this out

**Comment by sylarhcn** [comment]
it's a build bug，fixed in new version
