### ISSUE TITLE
请问在非沙盒扩展里如何访问VM内部

### ISSUE THREAD

**Issue by WP-Studio01** [Gandi-IDE/custom-extension#56]
如题

**Comment by DannyDevPro** [comment]
不会自己看node模块吗

**Comment by WP-Studio01** [comment]
还真不会
我是Scratch二开的小白



在 2022-12-17 21:22:40，"DannyDevPro" ***@***.***> 写道：

不会自己看node模块吗

**Comment by WP-Studio01** [comment]
（VS Code内部）
在哪里




在 2022-12-17 21:22:40，"DannyDevPro" ***@***.***> 写道：

不会自己看node模块吗

**Comment by WP-Studio01** [comment]
![image](https://user-images.githubusercontent.com/98379477/208281349-cfb01a13-f9cc-43b1-a883-d2eb36b41994.png)

**Comment by WP-Studio01** [comment]
好<del>霸霸</del>，教教我



在 2022-12-22 21:16:49，"DannyDevPro" ***@***.***> 写道：

无语

**Comment by sylarhcn** [comment]
看起来你是自己在搞 vm。
那你应该能看到每一个 extension 在被创建时都传入了一个 runtime ，用这个runtime 对象访问就可以了

**Comment by WP-Studio01** [comment]
runtime.vm访问报错



在 2022-12-25 22:20:32，"Nick" ***@***.***> 写道：

看起来你是自己在搞 vm。
那你应该能看到每一个 extension 在被创建时都传入了一个 runtime ，用这个runtime 对象访问就可以了

**Comment by bddjr** [comment]
`﻿runtime.extensionManager.vm`
